[build]
  command = "yarn install && NEXT_PUBLIC_BASE_URL=\"${NEXT_PUBLIC_BASE_URL:-$URL}\" yarn build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "${NEXT_PUBLIC_BASE_URL:-$URL}"
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    functions = ".netlify/functions"
    publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
