[build]
  command = "NEXT_PUBLIC_BASE_URL=\"${NEXT_PUBLIC_BASE_URL:-$URL}\" yarn install && yarn build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NEXT_PUBLIC_VERCEL_URL = "${URL}"
  NODE_VERSION = "20"
  YARN_VERSION = "1.22.19"
  NPM_FLAGS = "--no-optional"
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
